### ISSUE TITLE
ArmatureがScale1でないときにデフォルトの設定だと良く動作しない

### ISSUE THREAD

**Issue by Narazaka** [kb10uy/kb10uy-zatools#1]
ArmatureがScale100とか（FBX出力がアレなモデルしばしばある）だとOffset Distanceを0.00001とかにしないと良く動作しない（スカートがあらぬ方向に広がった感じとかになる）

なにか検知して初期値を変えるなり警告出すなりビルド時にScale吸収するなりする方法があるといいなあという気持ちです。

**Comment by kb10uy** [comment]
`fakeParent` を挿入した後に `(chainRoot.position - fakeParent.position).magnitude` を計算して元の値から一定割合以上離れてたら NDMF Console に警告を出す、あたりが丸いですかね
(Localizer を用意するのがだるくて NDMF Console 触るのを後回しにしてしまっていた)

**Comment by Narazaka** [comment]
一旦良さそうに思います（Offset Distanceを調整すると直るよ的な事が分かればよさそう）
