### ISSUE TITLE
やはりRotation Offsetが結構異なる事例がありそう

### ISSUE THREAD

**Issue by Narazaka** [kb10uy/kb10uy-zatools#2]
スカートの作りによりそうだが、Rotation Offsetが手動時と異なるのか変に広がる場合がある（断罪セーラーなど）。
Influenceが大きいと影響が顕著に出るので厳しくなる。
正確なoffsetを出す方法があったりしないか……（無知

**Comment by kb10uy** [comment]
Vector3 経由にすることで軸方向の回転が失なわれていたかも……

手動:
<img width="405" alt="Unity_1724846898_f2eTn" src="https://github.com/user-attachments/assets/fbeba013-f68b-489d-ab62-de714d2554a1">

`Quaternion.FromToRotation(middleQuaternion * Vector3.up, parentTransform.rotation * Vector3.up)`:
<img width="413" alt="Unity_1724847596_psLTa" src="https://github.com/user-attachments/assets/76eb2bc6-52af-4a08-b6c4-12b37d0f1312">

`Quaternion.Inverse(middleQuaternion) * parentTransform.rotation`:
<img width="412" alt="Unity_1724847391_DQWyb" src="https://github.com/user-attachments/assets/d3ef8a73-b9ef-444a-9389-2db32c053690">

`Quaternion.Inverse(middleQuaternion) * parentTransform.rotation` が正しい値の可能性が高そうです(360 - x を同じ角度とみなせるなら)
